version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -f Dockerfile -t amaksimov/python_data_science:latest .
      - run: docker push amaksimov/python_data_science:latest
  build_anaconda:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -f Dockerfile.anaconda -t amaksimov/python_data_science:anaconda .
      - run: docker push amaksimov/python_data_science:anaconda
workflows:
  version: 2
  build_images:
    jobs:
      - build
      - build_anaconda